version: '3.1'
services:
  myspring-mysql:
    image: mysql:8.0.20
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=myspring
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
  myspring-redis:
    image: redis:6.0.4
    ports:
      - '6379:6379'
