server:
  port: 9000
spring:
  #配置静态资源
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/
  #配置数据库
  datasource:
    url: jdbc:mysql://localhost:3306/myspring?allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    #放开预览页面不需要登录
    open-view-page: true
    #登录账号和密码
    user:
      name: "admin"
      password: "123456"
#Minidao配置
minidao:
  base-package: org.jeecg.modules.jmreport.*,org.jeecg.modules.drag.*
  #DB类型（mysql|postgresql|oracle|sqlserver|other）
  db-type: mysql
#输出sql日志
logging:
  level:
    org.jeecg.modules.jmreport: debug
